doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
#doctrine_migrations:
#    dir_name: '%kernel.project_dir%/src/Migrations'
#    namespace: DoctrineMigrations
