version: "3.4"
services:
  rainsimulator:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 81:80
    volumes:
      - .:/var/www/html
    image: rainsimulator
    container_name: rainsimulator
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD

  mysql:
    ports:
      - 33066:33066
    image: mysql
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql/data
volumes:
  mysql-data:
